name: ExecuteQuery_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.IBMDB2.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.IBMDB2.ExecuteQuery
      prebuild_command: docker run -h db2server --name db2server --restart=always --detach --privileged=true -p 50000:50000 --env-file ./Frends.IBMDB2.ExecuteQuery.Tests/lib/env_list.txt -v $PWD:/database icr.io/db2_community/db2
      env_var_name_1: LD_LIBRARY_PATH
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: /home/runner/.nuget/packages/net.ibm.data.db2-lnx/6.0.0.500/buildTransitive/clidriver/lib
      