name: ExecuteQuery_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.IBMDB2.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.IBMDB2.ExecuteQuery
      prebuild_command: chmod 777 ./_build/setup.sh && ./_build/setup.sh
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      