name: ExecuteQuery_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.IBMDB2.ExecuteQuery/**'
  workflow_dispatch:

env:
  LD_LIBRARY_PATH: /home/runner/.nuget/packages/net.ibm.data.db2-lnx/6.0.0.500/buildTransitive/clidriver/lib

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.IBMDB2.ExecuteQuery
      prebuild_command: chmod 777 ./_build/setup.sh && source ./_build/setup.sh
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      